//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherSys.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayTemperatures
    {
        public DayTemperatures()
        {
            this.Weather_Days = new HashSet<Weather_Days>();
        }
    
        public int ID { get; set; }
        public int day_temp { get; set; }
        public Nullable<int> day_min { get; set; }
        public Nullable<int> day_max { get; set; }
        public Nullable<int> day_eve { get; set; }
        public Nullable<int> day_morn { get; set; }
        public Nullable<int> real_feel_day { get; set; }
        public Nullable<int> real_feel_night { get; set; }
        public Nullable<int> night_temp { get; set; }
        public Nullable<System.DateTime> rowDatetime { get; set; }
    
        public virtual ICollection<Weather_Days> Weather_Days { get; set; }
    }
}
