//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherSys.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations
    {
        public Locations()
        {
            this.User_Locations = new HashSet<User_Locations>();
            this.Weather_Days = new HashSet<Weather_Days>();
        }
    
        public int ID { get; set; }
        public string Location_Name { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    
        public virtual ICollection<User_Locations> User_Locations { get; set; }
        public virtual ICollection<Weather_Days> Weather_Days { get; set; }
    }
}
