//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherSys.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles_Settings
    {
        public Profiles_Settings()
        {
            this.User_Locations = new HashSet<User_Locations>();
        }
    
        public int ID { get; set; }
        public int user_id { get; set; }
        public int sources_id { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Sources Sources { get; set; }
        public virtual ICollection<User_Locations> User_Locations { get; set; }
    }
}
