//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherSys.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sources
    {
        public Sources()
        {
            this.Profiles_Settings = new HashSet<Profiles_Settings>();
            this.Weather_Days = new HashSet<Weather_Days>();
        }
    
        public int ID { get; set; }
        public string Name_WeatherSource { get; set; }
    
        public virtual ICollection<Profiles_Settings> Profiles_Settings { get; set; }
        public virtual ICollection<Weather_Days> Weather_Days { get; set; }
    }
}
