//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherSys.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Profiles_Settings = new HashSet<Profiles_Settings>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public string PasswordHash { get; set; }
    
        public virtual ICollection<Profiles_Settings> Profiles_Settings { get; set; }
    }
}
