//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherSys.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Locations
    {
        public int ID { get; set; }
        public int settings_id { get; set; }
        public int locations_id { get; set; }
    
        public virtual Locations Locations { get; set; }
        public virtual Profiles_Settings Profiles_Settings { get; set; }
    }
}
