//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherSys.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weather_Days
    {
        public Weather_Days()
        {
            this.Weather_Hours = new HashSet<Weather_Hours>();
        }
    
        public int ID { get; set; }
        public int sources_id { get; set; }
        public int locations_id { get; set; }
        public Nullable<System.DateTime> weather_date { get; set; }
        public Nullable<decimal> rain { get; set; }
        public Nullable<int> wind_speed { get; set; }
        public Nullable<int> wind_degree { get; set; }
        public Nullable<decimal> pressure { get; set; }
        public Nullable<int> humidity { get; set; }
        public Nullable<decimal> clouds_range { get; set; }
        public int temperature_id { get; set; }
    
        public virtual DayTemperatures DayTemperatures { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Sources Sources { get; set; }
        public virtual ICollection<Weather_Hours> Weather_Hours { get; set; }
    }
}
